[workspace]
resolver = "3"

members = [
    "apps/cli", "crates/content",
    "crates/core", "crates/direct-link", "crates/discovery", "crates/identity",
    "crates/protocol",
    "crates/transfer",
    "crates/transport",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Risuleia/Rift"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "2"
tracing = "0.1"
